name: learn-github-actions
on: [push]
jobs:
  print-HelloWorld:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: echo "Hello World"
  
  run-python-code:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python

        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Move folder
        run: mv ./Downloads ~/Downloads
      - name: run program
        run: python main.py