name: learn-github-actions
on: [push]
jobs:
  print-helloWorld:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: echo "Hello World"
  
  Joni-for-sparken:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Joni for sparken"